## replace numpy with torch

### model
model_name_or_path: /dssg/home/acct-aemzl/aemzl-user1/modelscope_models/llama3-8b
quantization_bit: 4
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: delta
lora_target: all
lora_rank: 64
lora_alpha: 64

use_delta: true
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_verbose: 1

### dataset
dataset: gsm8k_train
template: default
cutoff_len: 1024
# max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /dssg/home/acct-aemzl/aemzl-user1/qbadam/saves/result_saves/llama3_delta_only_warmup_default_template_gsm8k_8epoch5e6

logging_steps: 10
save_steps: 1500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 5.0e-6
num_train_epochs: 8.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
# fp16: true
pure_bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
