### model
model_name_or_path: /home/ubuntu/date/mq_tst/quants_test/awq/autoawq/llama-3.2-1B-v0.2-awq
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 2
lora_target: all

### dataset
dataset: identity,alpaca_en_demo
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3.2-1b/lora/awq-sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 100
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 20
