### model
model_name_or_path: google/gemma-2-2b
quantization_bit: 4

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 64
lora_alpha: 64


### dataset
dataset: alpaca_gpt4_en
template: gemma
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/ubuntu/date/test-ckpts/gemma_lora_sft_bnb
logging_steps: 10
save_steps: 1500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 1000
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
